### ISSUE TITLE
VirusTotal marks the installer as a Trojan.

### ISSUE THREAD

**Issue by ElmorenohWTF** [AppsForDesktop/TikTok-desktop#1]
Link to VirusTotal analysis: https://www.virustotal.com/gui/file/379a812118605c50256716cd51262cb4743f29deb151f181fb163aecc6bc9550?nocache=1

Is it safe to install it? Why would VirusTotal report this? Is it a false positive?

![image](https://github.com/AppsForDesktop/TikTok-desktop/assets/62709646/8a677925-3d61-4203-9652-b7b4ddeeddc0)

**Comment by AppsForDesktop** [comment]
definitely it is a false positive, as you can check the code and there is nothing suspicious done by the program. And also only 3 of 66 AVs flagged it and in behavior section it tells nothing
I presume it flags it because the binary is not signed.

**Comment by ElmorenohWTF** [comment]
Windows Defender also marks it as a Trojan, as you can see here:
![ApplicationFrameHost_zPzdgXudRL](https://github.com/AppsForDesktop/TikTok-desktop/assets/62709646/b48fe33b-26d2-419c-844d-d9719d9a453c)
![ApplicationFrameHost_NsRf6SXvbP](https://github.com/AppsForDesktop/TikTok-desktop/assets/62709646/e58ee7f8-0a2c-4fae-9009-511bc45b06d2)

**Comment by AppsForDesktop** [comment]
It very strange, we will write a letter to Microsoft Windows defender support to ask what is the problem
